### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by whowazit** [TakahikoKawasaki/nv-websocket-client#41] opened 2016-03-11 06:27 UTC
There was WebSocketException buy I don't know who's fault it is either the android side or the server side.

W/System.err: com.neovisionaries.ws.client.WebSocketException: The status line of the opening handshake response is empty.
W/System.err: at com.neovisionaries.ws.client.HandshakeReader.readStatusLine(HandshakeReader.java:99)
W/System.err: at com.neovisionaries.ws.client.HandshakeReader.readHandshake(HandshakeReader.java:48)
W/System.err:     at com.neovisionaries.ws.client.WebSocket.readHandshake(WebSocket.java:2857)
W/System.err:     at com.neovisionaries.ws.client.WebSocket.shakeHands(WebSocket.java:2736)
W/System.err:     at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:1865)

**Comment by TakahikoKawasaki** [comment] 2016-03-11 06:41
When a WebSocket server accepts a request from a WebSocket client, the first line in the response from the server should be like the following.

```http
HTTP/1.1 101 Switching Protocols
```

Even when a server does not accept a request from a client, the first line in the response from the server must be an HTTP status line. For example, like this:

```http
HTTP/1.1 400 Bad Request
```

The error message you received indicates that the response from your WebSocket server did not contain even the first line. So, the behavior of your WebSocket server is wrong.

**Comment by TakahikoKawasaki** [comment] 2016-04-21 06:59
I close this issue because I think the root cause exists on the server side.

**Closed by TakahikoKawasaki** 2016-04-21 06:59 UTC

**Comment by shihabmi7** [comment] 2017-09-18 09:34
**Help**! **Help** !! It would be great if we got the server side code. Here is my socket.js code. I am also facing same problem. 

`var app = require('express')();
var http = require('http').Server(app);

var io = require('socket.io')(http);


io.on('connection', function(socket){
console.log('client connected');
	let jsonObject = {
		name: 'shihab',
		age : 28
	};

	io.emit('test-event', jsonObject);
	console.log(jsonObject);
});


http.listen(3000, function(){
	console.log('listenting on port 3000');
});

`

**Comment by iammeat** [comment] 2017-11-05 16:29
I had this issue with my app.  If you are using Let's Encrypt certificates or another authority that may not have a root CA in Android's trust store, you need to configure your sockets server to include the full certificate chain.

Let's Encrypt stores this in a file called fullchain.pem in the relevant folder under /etc/letsencrypt in Linux.  After I included this in my server configuration, my app started working properly.
