### ISSUE TITLE
WritingThread and ReadingThread leak mListenerManager ,and then leak WebSocket 

### ISSUE THREAD

**Issue by happycodinggirl** [TakahikoKawasaki/nv-websocket-client#67] opened 2016-07-04 03:59 UTC
Thank you for providing this,but i meet a question in my use. WritingThread and ReadingThread leak mListenerManager ,and then leak WebSocket ,which result in my  
 class not released. Do you have some suggestion to solve this ? Waiting for response , Thanks !

**Comment by happycodinggirl** [comment] 2016-07-04 04:21
i read the souce code of WritingThread and find that the main method has code `private void main()
    {
        mWebSocket.onWritingThreadStarted();

        while (true)
        {
            // Wait for frames to be queued.
            int result = waitForFrames();

            if (result == SHOULD_STOP)
            {
                break;
            }
            else if (result == SHOULD_FLUSH)
            {
                flushIgnoreError();
                continue;
            }
            else if (result == SHOULD_CONTINUE)
            {
                continue;
            }

            try
            {
                // Send frames.
                sendFrames(false);
            }
            catch (WebSocketException e)
            {
                // An I/O error occurred.
                break;
            }
        }

        try
        {
            // Send remaining frames, if any.
            sendFrames(true);
        }
        catch (WebSocketException e)
        {
            // An I/O error occurred.
        }
    }`

i don't know why use while(true) ,i think maybe this is the reason for my leak , do you think so?

**Comment by TakahikoKawasaki** [comment] 2016-07-05 07:36
The loop finishes eventually. Please check whether your application unintentionally holds some references to `WebSocket` instances somewhere.

**Comment by TakahikoKawasaki** [comment] 2016-12-25 15:55
`WritingThread`, `ReadingThread` and `ListenerManager` instances are created for each `WebSocket` instance. Therefore, if references to a `WebSocket` instance are released, references of `WritingThread`, `ReadingThread` and `ListenerManager` instances of the `WebSocket` instance will be released, too.

Please reopen this issue if you find the root cause of your issue in the implementation of nv-websocket-client.

**Closed by TakahikoKawasaki** 2016-12-25 15:55 UTC
